# Generated by Django 3.1.3 on 2020-11-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_player_score', models.IntegerField(blank=True, default=0)),
                ('right_player_score', models.IntegerField(blank=True, default=0)),
                ('winner', models.CharField(choices=[('UNDERFIND', 'Underfind'), ('LEFT', 'Left player won'), ('RIGHT', 'Right player won'), ('DRAW', 'Draw game')], db_index=True, default='UNDERFIND', max_length=20)),
                ('left_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_left_player', to='tournaments.tournamentparticipant')),
                ('right_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_right_player', to='tournaments.tournamentparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
