# Generated by Django 3.1.3 on 2020-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='stage',
            new_name='current_stage',
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='division',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Not assigned'), ('FIRST_DIVISION', 'First Division'), ('SECOND_DIVISION', 'Second Division')], default='NOT_ASSIGNED', max_length=20),
        ),
    ]
